config/routes.rb
Rails.application.routes.draw do
  resources :dreams
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  root "dreams#home"
  get 'about', to: 'dreams#about'
  # get 'contact', to: 'pages#contact'
  get 'lists', to: 'dreams#lists'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/dream.rb
class Dream < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/dreams_controller.rb
class DreamsController < ApplicationController
  before_action :set_dream, only: %i[ show edit update destroy ]

  # GET /dreams or /dreams.json
  def home
    @dreams = Dream.all
  end

  def about
  end

  def lists
    @dreams = Dream.all
  end

  # GET /dreams/1 or /dreams/1.json
  def show
  end

  # GET /dreams/new
  def new
    @dream = Dream.new
  end

  # GET /dreams/1/edit
  def edit
  end

  # POST /dreams or /dreams.json
  def create
    @dream = Dream.new(dream_params)

    respond_to do |format|
      if @dream.save
        format.html { redirect_to dream_url(@dream), notice: "Dream was successfully created." }
        format.json { render :show, status: :created, location: @dream }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @dream.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /dreams/1 or /dreams/1.json
  def update
    respond_to do |format|
      if @dream.update(dream_params)
        format.html { redirect_to dream_url(@dream), notice: "Dream was successfully updated." }
        format.json { render :show, status: :ok, location: @dream }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @dream.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /dreams/1 or /dreams/1.json
  def destroy
    @dream.destroy

    respond_to do |format|
      format.html { redirect_to dreams_url, notice: "Dream was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_dream
      @dream = Dream.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def dream_params
      params.require(:dream).permit(:title, :content)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/dreams_helper.rb
module DreamsHelper
end

app/views/dreams/_dream.html.erb
<div id="<%= dom_id dream %>">
  <p>
    <strong>Title:</strong>
    <%= dream.title %>
  </p>

  <p>
    <strong>Content:</strong>
    <%= dream.content %>
  </p>

</div>

app/views/dreams/_form.html.erb
<%= form_with(model: dream) do |form| %>
  <% if dream.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(dream.errors.count, "error") %> prohibited this dream from being saved:</h2>

      <ul>
        <% dream.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :title, style: "display: block" %>
    <%= form.text_field :title %>
  </div>

  <div>
    <%= form.label :content, style: "display: block" %>
    <%= form.text_area :content %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/dreams/edit.html.erb
<h1>Editing dream</h1>

<%= render "form", dream: @dream %>

<br>

<div>
  <%= link_to "Show this dream", @dream %> |
  <%= link_to "Back to dreams", dreams_path %>
</div>

app/views/dreams/home.html.erb
<p style="color: green"><%= notice %></p>

<h1 class="dream" >Dreams</h1>

<div id="dreams">
  <% @dreams.each do |dream| %>
    <%= render dream %>
    <p>
      <%= link_to "Show this dream", dream %>
    </p>
  <% end %>
</div>

<%= link_to "New dream", new_dream_path %>

app/views/dreams/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Dreams</h1>

<div id="dreams">
  <% @dreams.each do |dream| %>
    <%= render dream %>
    <p>
      <%= link_to "Show this dream", dream %>
    </p>
  <% end %>
</div>

<%= link_to "New dream", new_dream_path %>

app/views/dreams/lists.html.erb
<p>
    <ul>
        <li>lists 1</li>
        <li>lists 2</li>
        <li>lists 3</li>
    </ul>
</p>

app/views/dreams/new.html.erb
<h1>New dream</h1>

<%= render "form", dream: @dream %>

<br>

<div>
  <%= link_to "Back to dreams", dreams_path %>
</div>

app/views/dreams/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @dream %>

<div>
  <%= link_to "Edit this dream", edit_dream_path(@dream) %> |
  <%= link_to "Back to dreams", dreams_path %>

  <%= button_to "Destroy this dream", @dream, method: :delete %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Goal</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= stylesheet_link_tag "dream", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <%= javascript_include_tag 'dream', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="sidebar">
      <ul>
        <li><%= link_to 'Home', root_path %></li>
        <li><%= link_to 'About', about_path %></li>
        <li><%= link_to 'My lists', lists_path %></li>
      </ul>
    <%= yield %>
  </body>
</html>